#!/usr/bin/env python3
"""set-custom-icon.py -- set Finder flags on a MacBinary file.

    set-custom-icon.py <in.bin> <out.bin> [--name <MacBinary name>]
                       [--no-icon-flag] [--bundle]

WHY THIS EXISTS
---------------
A custom icon needs BOTH halves and neither works alone:

  (a) the icon family at resource ID -16455 (kCustomIconResource)
      -> icons/bt_icons.r, generated by scripts/custom-icon-to-r.py
  (b) the file's Finder flags with hasCustomIcon (0x0400) set
      -> this script

⚠⚠ --bundle (kHasBundle, 0x2000) IS A SEPARATE FLAG AND IS NOT IMPLIED BY ANYTHING.
A Control Strip module is built as a 'cfrg' fragment rather than an 'sdev' resource
for exactly one reason: only the fragment form can be DRAGGED OUT of the strip. That
behaviour needs the Finder to read the file's BNDL/FREF, and the Finder only does that
when kHasBundle is set. Without it the module still loads and still runs, so nothing
looks wrong -- the drag simply does nothing, and the whole reason for choosing the
harder build shape is silently thrown away.

This was shipped wrong once: csm/CMakeLists.txt claimed "the flag patcher still sets
kHasBundle" while this script only ever set kHasCustomIcon, so BTCsm 1.0 went out with
fdFlags=0x0000. cpu-temp's copy of this script had it right (FLAGS_HI=0x24) and the two
copies had drifted. ⇒ The flag is now explicit, and the readback below verifies it.

⚠ It is NOT wanted on every file this script touches: USBBluetoothSwitch is an
extension with no BNDL, and telling the Finder to look for one it does not have is the
same class of bug as --no-icon-flag exists to avoid.

Rez has no option for Finder flags, so the bit is set on the built MacBinary
afterwards. fdFlags live at MacBinary offset 73 (high byte) and 74 (low byte), so
hasCustomIcon is 0x04 in byte 73.

⚠ The MacBinary II header carries a CRC-16 over bytes 0..123 at offset 124, and
StuffIt Expander checks it. Touching byte 73 invalidates it, so it is recomputed
here. The CRC routine is the same one as firewire-fw800/rom/wrap-macbinary.py,
deliberately: that one is known to produce archives Expander accepts.

⚠ --name exists because Rez derives the MacBinary's INTERNAL filename from the
output path, so building via an intermediate "foo.raw.bin" would ship a file that
expands as "foo.raw". That name is what lands in the Extensions folder, and on
this project it is load-bearing: the USB Expert only scans files whose name begins
"USB". Always pass the name the file must have on the Mac.

Writes a NEW file rather than editing in place, per claude-os9/CLAUDE.md.
"""
import struct
import sys

kHasCustomIcon = 0x0400
kHasBundle     = 0x2000


def crc16(data):
    crc = 0
    for b in data:
        crc ^= b << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if crc & 0x8000 else (crc << 1) & 0xFFFF
    return crc


def main():
    args = sys.argv[1:]
    want_name = None
    if '--name' in args:
        i = args.index('--name')
        want_name = args[i + 1]
        del args[i:i + 2]
    # ⚠ For a file that carries NO icon family. USBBluetoothSwitch is renamed and
    # CRC-fixed by this script but ships no ICN#, and setting hasCustomIcon on a file
    # with no icon resource tells the Finder to go and find one -- which can render as
    # a BLANK icon rather than the generic 'ndrv' document. A blank icon in Extensions
    # reads as a corrupt file, which is the opposite of the intent (the switcher WANTS
    # to look plainly different from the driver, not broken).
    no_icon_flag = '--no-icon-flag' in args
    if no_icon_flag:
        args.remove('--no-icon-flag')
    want_bundle = '--bundle' in args
    if want_bundle:
        args.remove('--bundle')
    if len(args) != 2:
        print(__doc__.strip().splitlines()[2].strip())
        return 2
    src, dst = args[0], args[1]

    h = bytearray(open(src, 'rb').read())
    if len(h) < 128:
        print('ERROR: %s is too short to be MacBinary' % src)
        return 1
    nlen = h[1]
    if nlen == 0 or nlen > 63:
        print('ERROR: implausible MacBinary filename length %d' % nlen)
        return 1

    name = h[2:2 + nlen].decode('mac-roman')
    flags = struct.unpack('>H', bytes(h[73:75]))[0]
    ftype = bytes(h[65:69]).decode('mac-roman')

    # The flags this invocation is asking for, as one mask. Each is independent: an
    # icon family without a BNDL and a BNDL without an icon family are both legitimate,
    # and this script is used for both.
    want = 0
    if not no_icon_flag:
        want |= kHasCustomIcon
    if want_bundle:
        want |= kHasBundle
    wanted = ' | '.join([n for n, b in (('hasCustomIcon', kHasCustomIcon),
                                        ('hasBundle', kHasBundle)) if want & b]) or 'none'

    newflags = flags | want
    if newflags != flags:
        struct.pack_into('>H', h, 73, newflags)
        print('set-custom-icon: %r type %r  flags 0x%04x -> 0x%04x (%s)'
              % (name, ftype, flags, newflags, wanted))
    elif want:
        print('set-custom-icon: %r type %r  flags 0x%04x already carries %s'
              % (name, ftype, flags, wanted))
    else:
        print('set-custom-icon: %r type %r  flags 0x%04x LEFT ALONE (--no-icon-flag '
              'and no --bundle: this file carries neither)' % (name, ftype, flags))

    if want_name is not None:
        enc = want_name.encode('mac-roman')
        if not (1 <= len(enc) <= 63):
            print('ERROR: name %r is not 1..63 bytes' % want_name)
            return 1
        if len(enc) > 31:
            print('note: %r is longer than the HFS 31-char limit; the Finder will '
                  'truncate it' % want_name)
        if name != want_name:
            print('set-custom-icon: MacBinary name %r -> %r' % (name, want_name))
        h[1] = len(enc)
        h[2:2 + 63] = enc + b'\0' * (63 - len(enc))
        name = want_name

    old = struct.unpack('>H', bytes(h[124:126]))[0]
    new = crc16(bytes(h[0:124]))
    struct.pack_into('>H', h, 124, new)
    if old != new:
        print('set-custom-icon: MacBinary CRC 0x%04x -> 0x%04x (recomputed)'
              % (old, new))

    open(dst, 'wb').write(bytes(h))

    v = bytearray(open(dst, 'rb').read())
    # ⚠ The readback must verify what we ASKED FOR, in both directions. Checking only
    # "flag is set" would turn --no-icon-flag into a hard error on a correct file, and
    # dropping the check entirely would lose the guarantee for the normal path.
    got = struct.unpack('>H', bytes(v[73:75]))[0]
    if no_icon_flag and (got & kHasCustomIcon):
        print('ERROR: readback shows hasCustomIcon SET despite --no-icon-flag')
        return 1
    if not no_icon_flag and not (got & kHasCustomIcon):
        print('ERROR: readback shows hasCustomIcon is not set')
        return 1
    # ⚠ Verified in BOTH directions, like the icon flag: a --bundle that silently did
    # not take is precisely the failure that shipped in 1.0, and an unasked-for
    # kHasBundle would point the Finder at a BNDL the file may not have.
    if want_bundle and not (got & kHasBundle):
        print('ERROR: readback shows hasBundle is not set despite --bundle')
        return 1
    if not want_bundle and (got & kHasBundle):
        print('ERROR: readback shows hasBundle SET but --bundle was not asked for')
        return 1
    if struct.unpack('>H', bytes(v[124:126]))[0] != crc16(bytes(v[0:124])):
        print('ERROR: readback CRC does not verify')
        return 1
    vname = v[2:2 + v[1]].decode('mac-roman')
    if want_name is not None and vname != want_name:
        print('ERROR: readback name is %r, expected %r' % (vname, want_name))
        return 1
    print('set-custom-icon: wrote %s (%d bytes) as %r, flag/name/CRC verified'
          % (dst, len(v), vname))
    return 0


if __name__ == '__main__':
    sys.exit(main())
