#!/usr/bin/env python3
"""custom-icon-to-r.py -- turn a donor file's custom-icon family into Rez source.

    custom-icon-to-r.py <donor> <out.r>

⚠ RENAMED from icons-to-r.py, and the old name was a real bug. This script and
cpanel/scripts/icon-family-to-r.py both used to be called "icons-to-r.py" while doing
DIFFERENT things, which is the same collision that made the control panel ship a stale
MacBinary CRC for about twenty revisions under two scripts both named
set-custom-icon.py. It had already misfired here: because the generated-header string
below hardcoded a path, cpanel/bt_icon.r claimed to have been generated by THIS script
even though this one only ever emits ID -16455 and that file holds ID 128.

  * THIS script emits exactly ONE family, hardcoded to ID -16455, for a file's own
    Finder icon. Point it at a donor and you get the custom-icon resource.
  * icon-family-to-r.py emits EVERY family it finds at its REAL id, which is what
    several icons at distinct IDs (the panel's device icons at 200..205) needs.

Reaching for the wrong one fails silently rather than loudly: ask this script for a
set of numbered icons and you get a single -16455 family and no error at all.

<donor> is either a fork-ful file or the AppleDouble "._name" sidecar that macOS
writes beside it on an SMB share. Either way the icon family lives in the RESOURCE
fork, which is why the data fork of such a donor reads as 0 bytes.

WHY GENERATE REZ SOURCE INSTEAD OF READING THE FILE AT BUILD TIME
-----------------------------------------------------------------
Two reasons, both learned the hard way on this project:

1. Rez cannot `read 'ICN#'` a file -- the same trap as PICT resources, where the
   `read` form is a SILENT syntax error that leaves the resource simply absent.
   Emitting explicit `data` statements with hex is the form that works.
2. The donor lives on the Pi share, and the share is not always mounted (it
   dropped mid-session on 2026-08-31). A build must not depend on it. So the
   generated .r is committed to the repo and the build only #includes it.

WHAT A CUSTOM ICON NEEDS, BOTH HALVES
-------------------------------------
The resources alone do nothing. A file shows a custom icon only when
  (a) it carries the family at ID -16455 (kCustomIconResource), and
  (b) its Finder flags have the hasCustomIcon bit (0x0400) set.
This script does (a). scripts/set-custom-icon.py does (b), because Rez has no
option for Finder flags and the MacBinary CRC has to be recomputed afterwards.
"""
import struct
import sys

kCustomIconResource = -16455
WANTED = ('ICN#', 'icl4', 'icl8', 'icns', 'ics#', 'ics4', 'ics8')


def resource_fork(path):
    """Return the resource fork bytes, from an AppleDouble or a raw fork file."""
    d = open(path, 'rb').read()
    if len(d) >= 4 and struct.unpack('>I', d[0:4])[0] == 0x00051607:
        n = struct.unpack('>H', d[24:26])[0]
        for i in range(n):
            eid, off, ln = struct.unpack('>III', d[26 + i * 12:26 + i * 12 + 12])
            if eid == 2:
                return d[off:off + ln]
        raise SystemExit('ERROR: AppleDouble has no resource-fork entry')
    return d


def resources(rf):
    """Yield (type, id, data) for every resource in the fork."""
    dOff, mOff, dLen, mLen = struct.unpack('>IIII', rf[0:16])
    m = rf[mOff:mOff + mLen]
    tlOff = struct.unpack('>H', m[24:26])[0]
    ntypes = struct.unpack('>h', m[tlOff:tlOff + 2])[0] + 1
    for i in range(ntypes):
        e = tlOff + 2 + i * 8
        typ = m[e:e + 4].decode('mac-roman')
        count = struct.unpack('>h', m[e + 4:e + 6])[0] + 1
        rlOff = struct.unpack('>H', m[e + 6:e + 8])[0]
        for k in range(count):
            r = tlOff + rlOff + k * 12
            rid = struct.unpack('>h', m[r:r + 2])[0]
            dofs = struct.unpack('>I', b'\0' + m[r + 5:r + 8])[0]
            blen = struct.unpack('>I', rf[dOff + dofs:dOff + dofs + 4])[0]
            body = rf[dOff + dofs + 4:dOff + dofs + 4 + blen]
            yield typ, rid, body


def hexblock(b, indent='        '):
    out = []
    for i in range(0, len(b), 16):
        row = b[i:i + 16]
        pairs = ' '.join('%02X%02X' % (row[j], row[j + 1])
                         for j in range(0, len(row) - 1, 2))
        if len(row) % 2:
            pairs += ' %02X' % row[-1]
        out.append('%s$"%s"' % (indent, pairs))
    return '\n'.join(out)


def main():
    if len(sys.argv) != 3:
        print(__doc__.strip().splitlines()[2].strip())
        return 2
    donor, out = sys.argv[1], sys.argv[2]

    rf = resource_fork(donor)
    found = {}
    for typ, rid, body in resources(rf):
        if rid == kCustomIconResource and typ in WANTED:
            found[typ] = body

    missing = [t for t in WANTED if t not in found]
    if 'ICN#' not in found:
        raise SystemExit('ERROR: no ICN# at %d in %s' % (kCustomIconResource, donor))
    if missing:
        print('note: donor has no %s (fine, the Finder falls back)'
              % ', '.join(missing))

    with open(out, 'w') as f:
        f.write('/*\n')
        f.write(' *  %s -- custom icon family, GENERATED. Do not hand-edit.\n'
                % out.split('/')[-1])
        f.write(' *\n')
        f.write(' *  Regenerate with:\n')
        f.write(' *      scripts/custom-icon-to-r.py <donor> %s\n' % out)
        f.write(' *\n')
        f.write(' *  ID -16455 is kCustomIconResource, the Finder\'s "this file\'s own\n')
        f.write(' *  icon" slot. The resources are only half of it: the file also needs\n')
        f.write(' *  the hasCustomIcon Finder flag, which scripts/set-custom-icon.py sets\n')
        f.write(' *  on the built MacBinary.\n')
        f.write(' */\n\n')
        for typ in WANTED:
            if typ not in found:
                continue
            f.write("data '%s' (-16455) {\n%s\n};\n\n"
                    % (typ, hexblock(found[typ])))

    print('wrote %s: %s' % (out, ', '.join(t for t in WANTED if t in found)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
